---
platform: linux

inputs:
  - name: environment
  - name: deployment-tools
  - name: log-cache-ci
  - name: tile-src
  - name: tile-config
    optional: true
  - name: tile-version
  - name: metric-store-dev-release
  - name: metric-store-release
  - name: p-prom-telegraf-dummy-release
  - name: p-prom-prometheus-dummy-release
  - name: p-prom-cf-auth-proxy-dummy-release
  - name: p-prom-thanos-dummy-release

outputs:
  - name: baked-tile

params:
  OPSMAN_USER:
  OPSMAN_PASSWORD:
  # BLOBSTORE_ACCESS_ID: ((blobstore-access-id))
  # BLOBSTORE_SECRET_ACCESS_KEY: ((blobstore-secret-access-key))
  # OPSMAN_SSH_KEY: ((ops-man-ssh-key.private_key))
  TILE_NAME: o11y-store
  STEMCELL_URL:
  STEMCELL_SHA:
  PRODUCT_CONFIG_PATH:

run:
  path: log-cache-ci/tasks/bake_and_install/task
